[package]
name = "speedtest-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "speedtest_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["extension-module"] }
